DROP DATABASE IF EXISTS OOPTecDummy;
CREATE DATABASE OOPTecDummy CHARACTER SET utf8;

USE OOPTecDummy;

CREATE TABLE Movie_Detail(
    id INT UNSIGNED PRIMARY KEY,
    rating DECIMAL(3,1) DEFAULT 5.0 NOT NULL,
    duration SMALLINT UNSIGNED,
    year SMALLINT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    cover VARCHAR(255),
    date_inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Genre_Catalog(
    id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    genre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Serie_Detail(
    id INT UNSIGNED PRIMARY KEY,
    year_start SMALLINT UNSIGNED NOT NULL,
    year_end SMALLINT UNSIGNED,
    rating DECIMAL(3,1) DEFAULT 5.0 NOT NULL,
    name VARCHAR(100) NOT NULL,
    cover VARCHAR(255),
    date_inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE Episode_Detail(
    id INT UNSIGNED PRIMARY KEY,
    serie_id INT UNSIGNED NOT NULL,
    n_episode SMALLINT UNSIGNED NOT NULL,
    n_season SMALLINT UNSIGNED NOT NULL,
    rating DECIMAL(3, 1) DEFAULT 5.0 NOT NULL,
    duration SMALLINT UNSIGNED,
    name VARCHAR(100) NOT NULL,
    cover VARCHAR(255),
    date_inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (serie_id) REFERENCES Serie_Detail(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE MovieGenres_Master(
    movie_id INT UNSIGNED NOT NULL,
    genre_id TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (movie_id) REFERENCES Movie_Detail(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (genre_id) REFERENCES Genre_Catalog(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE SerieGenres_Master(
    serie_id INT UNSIGNED NOT NULL,
    genre_id TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (serie_id) REFERENCES Serie_Detail(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (genre_id) REFERENCES Genre_Catalog(id) ON UPDATE CASCADE ON DELETE RESTRICT
);